### ISSUE TITLE
leading/trailing spaces inside quotes are skipped

### ISSUE THREAD

**Issue by jaawerth** [motdotla/dotenv#197]
Hi!

I noticed this today while tinkering with a CLI script that serializes .env files that dotenv appears to be stripping leading and trailing whitespace from the values even when surrounded by quotes - is that intentional/a part of the .env syntax? I'm guessing not, since it would cause issues with, for example, passwords that contain leading/trailing spaces.

Test case (with v4.0.0):

**.env**
```
foo="    some value      "
```

**Output**
```
{ foo: 'some value' }
```

**Comment by maxbeatty** [comment]
The ".env syntax" is loosely based on INI file format. It is intentional that [dotenv "trims" values](https://github.com/motdotla/dotenv/blob/v4.0.0/lib/main.js#L30-L31). That "trimming behavior" has been around for almost 4 years ([see v0.0.1](https://github.com/motdotla/dotenv/blob/v0.0.1/lib/main.js#L18-L24)) and I think this is the first time it has come up in an issue. Maybe we should document in the README?

**Comment by jaawerth** [comment]
Thanks - and yeah, it did seem reminiscent of ini and I did a brief look around to see if there was a standard for the syntax but came up short in a quick google search - figured I'd ask.

Documenting sounds like a good idea - I expected the trimming without any quotes, but seeing it occur *with* the quotes took me a bit by surprise, since at that point the spaces would be there intentionally. Still, I suppose if wants the same sort of ini-like syntax without that behavior, there's always TOML. I only came across it because I was testing the parser against things I should account for in the serializer I was cooking up.

**Comment by cvuorinen** [comment]
I also ran into this issue as I need a value that has a leading space (don't ask, it's stupid I know but I can't change it in the receiving end).

IMO it would make more sense to trim only unquoted strings and leave quoted strings as is, because with quotes it's more obvious that the whitespace is part of the value.

e.g.
```
foo=    some value      
bar="    some value      "
```

would output:
```js
{
    foo: "some value",
    bar: "    some value      "
}
```

Should be pretty simple change, just swap the trim before the replace in this line: https://github.com/motdotla/dotenv/blob/40e9efcdc5495966d46540fefe786e8d2425b4b1/lib/main.js#L31
