### ISSUE TITLE
Why isn't dotenv a development dependency only?

### ISSUE THREAD

**Issue by tsongas** [motdotla/dotenv#216]
I'm curious why this is not put forward as a development dependency only i.e. `npm install --save-dev dotenv` since the whole idea is that it's only needed in development and not production?

**Comment by maxbeatty** [comment]
It's perfectly fine to use `dotenv` in production (or any environment for that matter). The easiest way to use this module is to require it in your source code (`require('dotenv').config()`). If you use it that way, you'll want it as a normal dependency.

If you want to preload dotenv (thus not having it in your source code e.g. `node -p dotenv/config server.js`) and only use it in certain environments (like your local machine), that's fine too! Do what works best for your situation.

**Comment by MJB-Khorasani** [comment]
so we can use it in both ways. we can use it as a devDependecy or Dependency

can you show how it is working (config)? please explain it to me. how it is know that where is the environmental variables and find set them?

**Comment by rubenx4p** [comment]
@MJB-Khorasani I can show you what I did:
This is my files of the projects, as you can see I had 3 different .env files.
![files-tree](https://user-images.githubusercontent.com/28691702/79039731-02575e80-7bec-11ea-82e7-cbd500a7780c.png)

And here you can see that I have few scripts.
The  first one is for Heroku so I dont need to configure dotenv because I already configured environment variable there.
The seconds and third I preload dotenv and change the path to load different files.
![scripts](https://user-images.githubusercontent.com/28691702/79039749-19964c00-7bec-11ea-8491-950bb4847a9f.png)

**Comment by galaux** [comment]
Sorry for the gravedigging but wanted to refresh this very convenient answer: it seems – as I'm writting – NodeJS's option is now `-r` rather than `-p` so the complete command is `node -r dotenv/config server.js`.
