### ISSUE TITLE
.env file is not read when config's path is a parent directory

### ISSUE THREAD

**Issue by jshado1** [motdotla/dotenv#217]
I have the following setup:
```
│ archetypes
│ ├─┬ config
│ │ ├─┬ webpack
│ │ │ ├── webpack.config.base.js
│ │ │ └── …
│ .env
```

In `webpack.config.base.js` I have:

```js
'use strict';

const envPath = path.join(process.cwd(), '.env');
console.log(`\n\nLOADING ${envPath}\n\n`);
const env = require('dotenv').config({ path: envPath });

console.log(env);
console.log(process.env);

// …
```

The output of `envPath` is correct.

The output of `env` is essentially empty: `{ parsed: {} }`.

`process.env` does not contain the environments set in `.env`.

**Comment by maxbeatty** [comment]
The default location is effectively `cwd` so you should be able to remove your path configuration to get the desired outcome.

```
| .env
| package.json
| path/to/some/webpack.config.js
```

```bash
npm run build
```

Because `npm` is being run from the "root" of your project, `dotenv` will load the `.env` file in the "root" of your project.

If you end up needing path configuration for some other reason, try `path.resolve` instead of `join` to get a full absolute path which helps `fs.readFileSync` under the hood.

**Comment by jshado1** [comment]
@maxbeatty I tried that first, and it didn't work. I just tried again, and the output of `process.env` still does not contain the contents of my `.env` file.

**Comment by jshado1** [comment]
Nvmd, I'm an idiot 😖 I included the `export `s from my .zshrc.
