### ISSUE TITLE
Feature request: Plugin system with hooks

### ISSUE THREAD

**Issue by zenflow** [motdotla/dotenv#240]
Currently there is no standard or built-in way to apply extensions to dotenv, and more importantly, composing extensions is not always easy or possible.

I see two approaches currently being used to building extensions
1. Use dotenv under the hood, like [dotenv-safe](https://github.com/rolodato/dotenv-safe)
2. Provide functions to be applied where dotenv is applied, like [dotenv-expand](https://github.com/motdotla/dotenv-expand)

- Type 1 extensions do not and will not compose with each other.
- Type 2 extensions will compose with each other (though you need to do the wiring manually). 
- Type 1 and 2 extensions will compose with each other *if and only if* the type 1 extension exports the same API as dotenv, meaning you cannot use any more extensions if you use packages like [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack), [ember-cli-dotenv](https://github.com/fivetanley/ember-cli-dotenv), etc.

I'd like to see a plugin system where plugins are passed in via an option and can use hooks like `preConfig`, `postConfig`, as well as hooks that give plugin developers more control over what happens during config.

That would enable plugins to be created that can be used _together_, _easily_.

**Comment by maxbeatty** [comment]
Perhaps this request would become clearer with a PR. Today, dotenv is two synchronous functions (`config` and `parse`) so any "hooks" would simply be:

```js
const { config } = require("dotenv")

function preConfig() {
  console.log("I am a preConfig hook")
}

function postConfig() {
  console.log("I am a postConfig hook")
}

preConfig();
config();
postConfig();
```

If you want a "hook" between parsing and assigning to `process.env`, you might want to write your own `config` function.

```js
const { parse } = require("dotenv")

module.exports = function myDotenvPlugin() {
  try {
    // TODO: insert pre-parsing logic

    const parsedObj = parse(stringOrBuffer)

    // TODO: insert post-parsing logic

    // this is copied directly from dotenv and that's perfectly fine
    Object.keys(parsedObj).forEach(function (key) {
      if (!process.env.hasOwnProperty(key)) {
        process.env[key] = parsedObj[key]
      }
    })

    return { parsed: parsedObj }
  } catch (ex) {
    return { error: ex }
  }
}
```

If dotenv can avoid a "plugin system" by another module copying some of our internal code, that's a preferable path forward since the other module gets complete control and dotenv stays minimal. Consumers wouldn't even have to be aware they are using dotenv's parsing logic or you could offer a drop-in replacement by having a matching API (i.e. `config()` returns `{ parsed: {}, error: null }`)

**Comment by zenflow** [comment]
@maxbeatty Thanks for taking the time to help me with this, and I'm sorry that I haven't made the problem too clear

> If dotenv can avoid a "plugin system" by another module copying some of our internal code, that's a preferable path forward since the other module gets complete control and dotenv stays minimal

But then we can't combine extensions. If I create a dotenv-recursive module in the way you suggest (taking complete control) users wouldn't be able to use it with dotenv-safe, since it also assumes complete control. They might end up creating a dotenv-recursive-safe module, that uses dotenv-recursive under the hood and copies logic from dotenv-safe (or vice-versa), in which case they're not actually using dotenv-safe and they miss out on that community (bug fixes, enhancements, discussions, etc.). And what about when they want to use dotenv-expand too? Time to make a new package dotenv-recursive-safe-expand? Yeesh.

Only one module can have complete control, and I think ideally that module is dotenv and it has the ability to delegate to multiple plugins as desired by the end-user. I think a plugin system like this would be a good approach to keeping dotenv minimal (keeping features in user-land) while allowing end-users to use any combination of [compatible] features (without creating a new package for each combination).

Note there are some packages that use dotenv under the hood, out of necessity, since they are not-so-much extensions as they are adaptors, such as babel-plugin-inline-dotenv, dotenv-webpack, ember-cli-dotenv, etc. You'd never want to combine adaptors, but you might want to use an extension with an adaptor (as I very much do; dotenv-recursive with babel-plugin-inline-dotenv). Without a plugin system I'd have to create babel-plugin-inline-dotenv-recursive (just to change the dependency in package.json from dotenv to dotenv-recursive), but with plugin system, I would simply configure babel-plugin-inline-dotenv with something like:

**.babelrc**
```
{
  "plugins": [["inline-dotenv", {
    "encoding": "base64",
    "plugins": ["dotenv-recursive"]
  }]]
}
```

The `plugin` option would be passed directly to dotenv, and no special version of babel-plugin-inline-dotenv would be needed. 

The details of how the plugin system would work would require a bit of careful thought, so I want to avoid making a PR until this idea has some more support.

Thoughts?

**Comment by maxbeatty** [comment]
That’s a lot of FUD for problems that don’t yet exist. I’m pretty confident you can achieve the outcome you’re after without a plugin system. Instead of approaching the problem with the mindset of executing some extra logic during dotenv’s execution, what if you did all of the work ahead of time. 

1. Find all files in a tree that matches a name like ".env"
2. Sort the found paths for the order you desire (child first or most distant parent first)
3. Concatenate the files contents 
4. Write the result to a single (temporary) file
5. Return the path to this new single combined file

Now, you can pass that path to any existing dotenv module and get the desired outcome of loading multiple .env files in a recursive manner. This new "recursive file concatenator" module can focus on efficient file searching and dotenv can continue to focus on parsing a single file.

**Comment by zenflow** [comment]
In this way I can achieve the outcome I want in regards to the feature idea in #238, but aside from that, it is unfortunate that I'll have to either fork babel-plugin-inline-**dotenv** into babel-plugin-inline-**dotenv-safe**, or just forget about using the feature in dotenv-safe.

**Comment by zenflow** [comment]
Feel free to close this issue. 

Thanks for your help.
