### ISSUE TITLE
Is this repo/package maintained?

### ISSUE THREAD

**Issue by elektronik2k5** [motdotla/dotenv#254]
First, thank you @motdotla for creating this package! :bowing_man: 
Looks like the last release to npm was a year ago and since then a few bugs have been fixed and features added (including a pending PR).

Given the fact this is a very useful and popular package, which is depended on by thousands of packages, can you please release a new version? Are you looking for maintainers? Can I help?

**Comment by jcblw** [comment]
@elektronik2k5 it also looks like latest is on NPM and the pending pr is just error messaging. 

I think we have only been getting feature request.  Most of which we end up closing due to us wanting to keep the core small. We are always looking for maintainers, but I also know we are not looking to add many new features to this library. 

Is there something you are concerned with or is it just that we have not published a new version lately?

**Comment by maxbeatty** [comment]
[This project](https://github.com/motdotla/dotenv/projects/1) outlines the release blockers (#241 may not make it). I haven't received any feedback on #237. Once that is merged, v5 should be released shortly after.

**Comment by elektronik2k5** [comment]
@jcblw latest __release__ is on NPM, but why not also release non breaking changes as a minor version, as well as breaking changes as a "next" or "beta" tag?
@maxbeatty, thanks, I wasn't aware of that work and am not used to seeing repos adopting GitHub projects.

**Comment by maxbeatty** [comment]
The "next" or "beta" tag strategy doesn't have the same upside for a small, stable module like dotenv. If you need the latest before a release, installing directly from GitHub is the way to go.

```
npm install motdotla/dotenv
```
