### ISSUE TITLE
Cannot set NODE_OPTIONS 

### ISSUE THREAD

**Issue by cemremengu** [motdotla/dotenv#314]
This may not be related to `dotnev` but I am trying to set  `NODE_OPTIONS="--max-old-space-size=8192"`  and looks like it does not work (my app crashing is how I check 😄 )

I do `require('dotenv').config({ path: '.env' });` at the beginning of script, I also tried preloading but none of them seems to work.

Is this the right way to set this setting via dotenv?

**Comment by maxbeatty** [comment]
[NODE_OPTIONS](https://nodejs.org/dist/latest-v8.x/docs/api/cli.html#cli_node_options_options) looks to be a special case. Remember `dotenv` will not overwrite existing environment variables. I'm not really familiar with `NODE_OPTIONS` but it looks like it's intended to alter how the process (and child processes) behave whereas `dotenv` is more intended to help how your app code behaves (e.g. connect to this database instead of that database)

**Comment by maxbeatty** [comment]
Please reopen if there's something `dotenv` can do to set this special env var

**Comment by mbana** [comment]
Is this supported? I'm also looking for a way to specify `NODE_OPTIONS` in the `.env` file.

Also,

> Remember dotenv will not overwrite existing environment variables.

Can you allow variables to be overwritten by requiring the user to explicitly set a parameter, say? E.g., `ALLOW_OVERWRITE`?

**Comment by basaran** [comment]
I think the issue is, by the time dotenv is alive, node is already running. Your best bet is to add it to your script file or set it through the os which one method is via `/etc/environment`.

For your `packages.json`, syntax for 4GB allocation would be:
```
"start": "NODE_OPTIONS=--max_old_space_size=4096 nodemon ./src/start.js"
```

You can then use the v8 module to see if the allocation has succeeded:

```
const v8 = require('v8);
console.log(v8.getHeapStatistics().total_available_size);
```

**Comment by ivan-kleshnin** [comment]
> I think the issue is, by the time dotenv is alive, node is already running.

Even if you CLI `dotenv` there's the issue with priorities. To workaround that you can `unset` system-wide value before calling or importing dotenv.

```
unset NODE_OPTIONS && dotenv -e=.env.local -e=.env -- node server.js --host=127.0.0.1 --port=3000
```
