### ISSUE TITLE
Trailing spaces in .env file cause parsing problems

### ISSUE THREAD

**Issue by jacbop** [motdotla/dotenv#322]
## .env file
```
A="a value"
B="another value but with two trailing spaces"  
```

## .env characters
note the trailing whitespace after the double quote on the last line
```
$ od -a .env
0000000   A   =   "   a  sp   v   a   l   u   e   "  nl   B   =   "   a
0000020   n   o   t   h   e   r  sp   v   a   l   u   e  sp   b   u   t
0000040  sp   w   i   t   h  sp   t   w   o  sp   t   r   a   i   l   i
0000060   n   g  sp   s   p   a   c   e   s   "  sp  sp  nl
0000075
```

## index.js
```javascript
$ cat index.js
require('dotenv').config()
console.log(process.env.A)
console.log(process.env.B)
```

## output
```
node ./index.js
a value
another value but with two trailing spaces"
```

That trailing double quote should not be there

**Comment by maxbeatty** [comment]
because you have trailing spaces after your quotes, [our regex](https://github.com/motdotla/dotenv/blob/v6.0.0/lib/main.js#L30) isn't removing the last quote (`['"]$`). additional logic could be added to account for that whitespace but I haven't fully thought through the pros and cons.

if you're looking for a quick workaround, make sure `"` is the last character on the line

**Comment by fportela-ns** [comment]
if you do want the trailing spaces try setting the value without quotes, like:
`B=another value but with two trailing spaces  `

there's a [test](https://github.com/motdotla/dotenv/blob/master/tests/test-parse.js#L38) for this:
`t.equal(parsed.INCLUDE_SPACE, 'some spaced out string', 'retains spaces in string')`
