### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by george-norris-salesforce** [motdotla/dotenv#333]
Added private RSA key to `.env`. Using it to sign a JWT.
When I sign the JWT, this error greats me.

`error:0906D066:PEM routines:PEM_read_bio:bad end line`

My RSA key is just a basic multi line, key.
```
-----BEGIN RSA PRIVATE KEY-----
MIIEpgIBAAKCAQE.......
........
```

The instructions as I understand are to add a `\n` to the end of every line? And then make this string a one liner? But seems there is still some whitespace bad character is still happening
Any solutions to fix this problem?

**Comment by george-norris-salesforce** [comment]
Figured it out, had a white space character in between a \n

**Comment by tom-sherman** [comment]
May I suggest a syntax?
I'd envisage newlines being preserved and each line to be trimmed so that you can nicely indent a long value.

```
multiline_string=this string is \
long and has more \
than one line
```

Prior art:
* [TOML multiline strings](https://github.com/toml-lang/toml/blob/master/README.md#string)
* [The many ways in which this is possible in YAML](https://yaml-multiline.info)

It's worth noting that some minimal formats, notably `ini`, don't allow multiline strings at all.

**Comment by maxbeatty** [comment]
fwiw we've been following `ini` spec albeit loosely
