### ISSUE TITLE
Exception when `.env` file is not found

### ISSUE THREAD

**Issue by eddiemf** [motdotla/dotenv#352]
I was trying to run a node script that relies on `.env` in Jenkins after checking out the data from my repo, so of course `.env` wasn't fetched since it's in `.gitignore`. The problem is that the `config()` method returns only an `error` property when the file is not found, making all access to the `parsed` property return undefined, so trying something like `const ip = env.parsed.ip` breaks the script since `parsed` is undefined.

I suppose there's no way of getting through this without explicitly checking for errors or undefined `parsed` property, am I right?

I think making this method return an empty object in its `parsed` property would solve it without causing any additional validation steps, while still allowing for checks for the `error` property and not breaking the script. 

What do you think?

**Comment by maxbeatty** [comment]
There’s a few ways around this.

1. Use `process.env.IP` instead of the parsed object. The parsed object is mostly exposed for further processing or validation. Your code will need to be able to handle undefined values still.
2. Configure your CI with environment variables. I think with Jenkins this is defined in their interface for the job. Alternatively, you could create something like `.env.ci` that’s not git-ignored and dynamically configure dotenv to use it (remember to use safe-to-share defaults like 1.1.1.1)

**Comment by eddiemf** [comment]
Great alternatives, thanks for the support :)
