### ISSUE TITLE
How to ignore env variable substitution

### ISSUE THREAD

**Issue by hibangun** [motdotla/dotenv#359]
I have key something like this
```
XXX_KEY="~3W`VA8;MEL$|O4fq<IkKOWou;+>GU3$OHoC?J:^`O(kKg"
```

but dotenv read it something like this
```
XXX_KEY="~3W`VA8;MEL$|O4fq<IkKOWou;+>GU3?J:^`O(kKg"
```

So we are missing `$OHoC`, how do I ignore that?

**Comment by maxbeatty** [comment]
dotenv doesn't do any substitution. are you using another module for that?

**Comment by huntie** [comment]
I'm experiencing this behaviour, using this library alone.

It looks like the sheer `process.env` assignment in `main.js` causes shell variable substitution to take place. This breaks string values which include `$` characters followed by an alphanumeric string - substituting these for an empty string.

**Test with sample env file**

N.B. This is output using [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) but I have added log statements in the installed version of this package.

Regardless of whether the string is quoted or not.

![image](https://user-images.githubusercontent.com/2547783/81321353-6570cf80-908a-11ea-9f9a-8162cc4c60c9.png)

**Further notes**

- This **cannot be fixed** by users through "escaping" an input string with `\$`.
- This is not the behaviour of `.env` implementations for other languages.
- This can be fixed with a `.replace('$', '\\$')` on each `val` before the `process.env` assignment. **Fixing this is going to be a breaking change**. Can't guarantee that all users relying on this behaviour are using [dotenv-expand](https://github.com/motdotla/dotenv-expand).

Given this can't be worked around by users, I would recommend reopening this issue.

**Comment by agatheblues** [comment]
Escaping the `$` with `\\$` did work for me 🍰 !
