### ISSUE TITLE
💵👩🏻‍💻 Working Capital - Ethereum, OpenCollective, TideLift, ...

### ISSUE THREAD

**Issue by lastmjs** [motdotla/dotenv#419]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a canonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have an Ethereum address in their package.json file. 

Having an Ethereum address would allow various cryptocurrencies to be donated, including stablecoins pegged to USD, like USDC or DAI. Essentially it is another payment network like PayPal, but open and decentralized like the internet. Getting an address is relatively straightforward through something like MetaMask or Coinbase. You could also generate one on your own.

**Comment by motdotla** [comment]
@lastmjs I love the idea of an application that would help users easily donate via crypto. Being programatic, I think crypto will better (at least in a technical/automated sense) solve the donation problem for software usage than other forms of money.

I even did a little work myself toward this aim, but ASICs rendered it dead on arrival. The hypothesis was that it would be easier for companies to donate their CPU cycles to open source maintainers than their cash. Less friction. https://github.com/motdotla/oscnode

That said, from a maintainers view point (at least in the United States), the hardest thing is actually organizing the incoming money in a legal way for reporting. Do I need a bank account? What are tax implications, etc? And the 2nd hardest thing is distributing the money to each contributor of the repository. (I'd ideally like to contribute to those individuals who answer issues as well) How do I pay them for their work? How do I send the money across borders? How do I decide how much one contributor should be paid over another?

It can be a lot of extra work that just distracts and detracts from the life I want to live - one spent programming.

Sometimes I daydream that GitHub or NPM or Rubygems or the entire open source developer community was more like a video game. You grind out XP or some other token and can exchange that 'in-game' for something else. Stars and downloads are essentially that but aren't exchangeable for anything. They are kind of fun, but not as fun as a video game.

So that is a long winded way to say, we are not going to do the Ethereum address. On the surface it looks like low hanging fruit but in practice it will require a lot of effort on the maintainers' parts - exactly what we want to avoid for already busy maintainers.

**Comment by lastmjs** [comment]
Makes sense! Seems like Open Collective or GitHub or npm might need to integrate something like this natively...or my service would need the legal framework provided, which Open Collective seems to already be doing a good job of

**Comment by motdotla** [comment]
Leaving this ticket open though and changing the title to 'Working Capital'. Thanks for getting the ball rolling @lastmjs.

...

For anyone reading this:

Do you use dotenv?

Has it helped make security easier for your company?

Has it helped make you a better software professional?

...

A fair amount of effort has been put into dotenv by some great contributors and I would like to somehow reward them for that. But I'd also like to find a mechanism to sustainably reward them.

If you were to donate or somehow otherwise contribute how would you prefer to do it? Bitcoin, Ethereum, GitHub, OpenCollective, TideLift, big fat banner add (no tracking) on the README, CPU donations, infrastructure credits, something else?

We would love to hear all ideas - crazy or otherwise. What would you hate, what would you love?
