### ISSUE TITLE
variables with backslash

### ISSUE THREAD

**Issue by selmi-karim** [motdotla/dotenv#468]
failed to load variables with backslash character.

sandbox link: 
https://codesandbox.io/s/hardcore-nash-cj4j3

.env file
`password=hello\pingo
`

output:
`process.env.password = hello\\pingo
`

> node version : 12.16.2
> npm version : 6.14.4
> dotenv version : ^8.2.0

**Comment by ziafok** [comment]
try: 
.env file
password=hello\\pingo

**Comment by jcblw** [comment]
@selmi-karim sorry for the late reply. I just looked at your sandbox. I think what you are seeing that in the node process is thinking you are escaping the character "p" in your example which is why it wants a double slash to escape the escape char. You can also see this through the linting errors of that example that it is escaping the "p".

Also was able to confirm with a dotenv file of:
```
# .env
SECRET=foo/bar
```
and then running
```sh
node -r dotenv/config -e "console.log(process.env.SECRET)"
```
the output is "foo/bar" with no extra slash.

If you pull the value "hello\pingo" from a db or have it stored somewhere outside of the source code you should not run into this double slash issue. 

Let me know if that helps. 

Closing this issue since it seems that this is not unwanted behavior in the library.

**Comment by lokimckay** [comment]
> Closing this issue since it seems that this is not unwanted behavior in the library.

So it is not possible to load an environment variable that contains a backslash?

I need to load this
```shell
AZURE_USER=dev-****\$dev-****
```

but as described above it produces

```
AZURE_USER=dev-****\\$dev-****
```

Surrounding the variable with quotes does not help

```shell
AZURE_USER='dev-****\$dev-****'
AZURE_USER="dev-****\$dev-****"
# still produces
AZURE_USER='dev-****\\$dev-****'
AZURE_USER="dev-****\\$dev-****"
```

It should be possible to deactivate the escaping somehow IMO

**Comment by rakunkel-ucd** [comment]
I have the same issue.

**Comment by motdotla** [comment]
reopening this

**Comment by eladchen** [comment]
Why no just write an adhoc function that replaces double backslashes "\\"  with "\"?

**Comment by cheng-alvin** [comment]
@motdotla I would close this due to inactivity

**Comment by cheng-alvin** [comment]
All good mate, do need me to review or merge PRs (Pull requests)?

Alvin.
________________________________

**Comment by semmel** [comment]
> Why no just write an adhoc function that replaces double backslashes "\" with ""?

Does not work; What if it is intended to be a double backslash?

Need to invent my own escape-pattern:
```env
AZURE_USER='dev-****<de.company.app.escape>\$dev-****'
```

test it
```js
const replacer = s => s.replace("<de.company.app.escape>\\", "");
const s = String.raw`dev-****<de.company.app.escape>\\$dev-****`;
replacer(s);
// -> dev-****\$dev-****
```

Is there any way to feed such a `replacer` into the dotenv parser?

**Comment by motdotla** [comment]
we fixed this as some point in time.

working example here: https://github.com/dotenv-org/examples/blob/master/usage/dotenv-nodejs-backslash/.env

<img width="768" alt="Screenshot 2024-02-05 at 3 46 55 PM" src="https://github.com/motdotla/dotenv/assets/3848/76e11372-8996-48e7-935f-70845e45372a">
