### ISSUE TITLE
Option to set .env options

### ISSUE THREAD

**Issue by AdamKearn** [motdotla/dotenv#477]
Hi Guys,

It would be cool if there was an option to set options in the .env file.
Forgive me if I have missed something,   But when I was looking at the documentation I couldn't see anything related to this?

I was thinking something like the following would be good. 
```
const dotenv = require('dotenv');
dotenv.set( [{key, value}, {key, value}] );    # Append the key/value pairs to the .env file.
```

**Comment by sai1139** [comment]
On application start all environment values will load one time, not every time.
If we are setting new  env values in .env file how it will load again and 
On build / production how can be possible?

**Comment by AdamKearn** [comment]
@sai1139 After re-reading my comment above, I realised I didn't make much sense.

I am looking for a way to write entry's to the .env file for next time my script runs.

**Comment by jcblw** [comment]
Hey there @AdamKearn I like the idea of allowing some config to be set in these files via user input. That being said I am not sure that it makes sense to add this to the core library. It should be a small amount of code to write these values and calling `dotenv.config` again would reload those values. 

I am interested to see how this comes out, but I am going to close this ticket since we will not be adding this to the core library. Also please feel free to reach out here if you have any questions about writing this data to the .env file.
