### ISSUE TITLE
Swallow Errors?

### ISSUE THREAD

**Issue by four43** [motdotla/dotenv#481]
Why does this swallow errors by default? That seems like a terrible idea.

It's recommended to add:
```
if (result.error) {
  throw result.error
}
```
???

**Comment by jcblw** [comment]
Hey there thanks for the issue. Although it would be useful for development issues to allow dotenv to fail fast by throwing. I do not think it would be optimal for production builds, especially since this can result with an error if the *.env* file is not present. Not having a *.env* file in production is very common. 

Thanks again for your suggestion, but I think we will allow users to define that behavior if they want for env to work that way.

**Comment by four43** [comment]
Def could be a pretty breaking change at this point. Fair enough! Thanks for the response
