### ISSUE TITLE
Support package.json “config” object

### ISSUE THREAD

**Issue by roydukkey** [motdotla/dotenv#485]
Are there interests or use cases for supporting the [package.json “config” object](https://docs.npmjs.com/misc/scripts#special-packagejson-config-object)?

I this would require a small update to `dotenv/lib/env-options.js`, checking for these three variable:

```
npm_config_DOTENV_CONFIG_ENCODING
npm_config_DOTENV_CONFIG_PATH
npm_config_DOTENV_CONFIG_DEBUG
```

The npm "config" variables would be secondary to the current implementation.

I would be willing to create a PR.

**Comment by BigBlueHat** [comment]
You can just `const pkg = require('package.json');` if you wanted to get access to stuff you record in that file.

However, you don't want (most) config parameters in the `package.json` file because configuration should be considered local/runtime state and not universally/globally applicable--i.e. [store config in the environment.](https://12factor.net/config)

**Comment by motdotla** [comment]
The interest for this is currently small so I'm going to go ahead and close.
