### ISSUE TITLE
Docs: 12-factor

### ISSUE THREAD

**Issue by ggggr** [motdotla/dotenv#490]
Please don't quote the 12-factor.
The splitting of the code and the configuration is not done properly.

* dotenv embed the config inside the built code (the config should be store in env : https://12factor.net/config
* the build can only be installed in one environment, this violates : https://12factor.net/build-release-run

**Comment by BigBlueHat** [comment]
Steps to use dotenv that _are_ 12 Factor friendly:
1. Add `.env` to your `.gitignore` file.
2. Provide a `.env.sample` (or similar) with the basic configuration values required.
3. One the dev (or uat, or production, etc.) server create a `.env` file from `.env.sample with the local, runtime configuration.

Just because you can add the file to the built code, doesn't mean you should.
