### ISSUE TITLE
Dotenv Should Allow Escaped Characters in Double Quoted Strings

### ISSUE THREAD

**Issue by craig-riecke** [motdotla/dotenv#496]
The following code works in Bash:

```
$ cat .env
ENV_WITH_DOLLAR_SIGN="Money\$"
$ source .env
$ echo $ENV_WITH_DOLLAR_SIGN
Money$
```

But the escape character is not recognized as such by dotenv:

```
$ cat index.js
const dotenv = require('dotenv');

dotenv.config()
console.log(process.env.ENV_WITH_DOLLAR_SIGN);
$ node index.js
Money\$
```

Although there's no technical requirement that dotenv should follow Bash, it's kind of implied since that's where the "Dotenv format" was started.  The Ruby version of dotenv (on which this is based) follows Bash convention as well.

**Comment by garygreen** [comment]
This is especially important when defining paths for us mere mortal window users. E.g:

```
PDF_BIN="\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
```

This should in theory output a string that is contained in quotes.

It's worth noting this use to work with older versions of dotenv when we were on Laravel 5.4, since upgrading to newer version of Laravel which uses an updated version of dotenv we can't seem to get the same behaviour.

**Comment by jimmcslim** [comment]
Noticing this myself, working with latest version of `create-react-app`. How to deal with an API key that contains `$` characters?

**Comment by motdotla** [comment]
this conversation was spread over a few threads. unifying here: https://github.com/motdotla/dotenv/issues/521
