### ISSUE TITLE
Not working after installing 1.0

### ISSUE THREAD

**Issue by drewhamlett** [motdotla/dotenv#60]
```
.env

NODE_ENV=development
PG_URL=postgres://blah@localhost:5432/cool
```

```
.env.development

PG_URL=postgres://wtf:wtf@development:1234/development
```

```
0.5.1 > process.env.PG_URL === postgres://wtf:wtf@development:1234/development
```
```
1.0.0 > process.env.PG_URL === postgres://blah@localhost:5432/cool
```

**Comment by jcblw** [comment]
we removed the feature of environment specific .env files in 1.0

**Comment by motdotla** [comment]
Indeed. Optionally you can now use the config method to point to them. But we recommend the best practice of a single .env local to your environment.

**Comment by drewhamlett** [comment]
How do you have a single .env if you have a development environment and testing environment?  Just trying to figure out best practice.

**Comment by maxbeatty** [comment]
@drewhamlett this is easiest if you keep .env out of source control. You'll want to create a .env for each environment (development and testing in your example). If any values are the same across environments, it's not really an environment variable :smile_cat: 

development environment:

```
NODE_ENV=development
PG_URL=postgres://wtf:wtf@development:1234/development
```

testing environment:

```
NODE_ENV=testing
PG_URL=postgres://blah@localhost:5432/cool
```

Happy to provide more real-world examples if that would be helpful

**Comment by jeffkole** [comment]
The ship may have sailed, but I can offer another real-life example of when environment-specific files can be helpful: local integration tests.

For our integration tests, we delete our database and recreate it so that it is pristine between tests.  The tests run against a clean database and are responsible for setting up the data they need.  Instead of blowing away all of the data in the local databases we use during development, we have a separate local database for testing and reference its URL by using a `.env.test` file.

Sadly, when I upgraded `dotenv` on Monday and ran `npm test` everything worked, but the data that I had set up for use when doing development work and manual validating of features was all gone.  My two options now are to not upgrade `dotenv` or to figure out a new way of managing the testing database.

**Comment by maxbeatty** [comment]
@jeffkole you can still use your `.env.test` file by loading it first. See #63 for [example](https://github.com/motdotla/dotenv/issues/63#issuecomment-89467300). 

If only your database names follow a convention like `app` and `app_test`, you could have your integration tests prepare them without needing an additional `.env.test` file (assuming database name is the only difference)

```js
process.env.db_name = process.env.db_name + '_test'
```

You could also look to run your app in a container to isolate environments. Hope this helps your situation.

**Comment by kevinSuttle** [comment]
I can't get dotenv to work either. I have one .env file and a config.js that is populated with `process.env` values. It seems to be a race condition as my config file is never populated.

Express app: /bin/www. First line.
```javascript
var dotenv = require('dotenv').load();
var config = require('../config');
console.log(config);
...
```
**Console**
```
dbName: undefined,
        host: undefined,
        URL: undefined,
        user: undefined,
        account: undefined,
...
```

**Comment by jcblw** [comment]
@kevinSuttle I don't think this is the same issue, please open up a separate issue and please give more insight on how config is being written. Chances are if you log out process.env and the `dotenv` variables are there then there is not much this library can fix.

**Comment by motdotla** [comment]
@kevinSuttle That does look like a separate issue. Can you open in a separate issue, and share your `config.json` file code. We'll take a look from there and help you debug.

Closing this issue.
