### ISSUE TITLE
# inside double quotes still treated as inline comment

### ISSUE THREAD

**Issue by Devtronyx** [motdotla/dotenv#601]
v14.2.0
`SOME_KEY={"field1":"some value", "field2": "stops here#this is discarded"}`
When above line is parsed generates the following output
`SOME_KEY: {"field1":"some value", "field2": "stops here`
which in turns gives a SyntaxError: Unexpected end of JSON input

**Comment by motdotla** [comment]
Thank you for raising this. We are looking into it. Anyone else this is happening to, please +1.

**Comment by jonathan-reisdorf** [comment]
@Devtronyx interesting. In this case, even though it's a json this is read as a string. You'd have to quote the entire value in order to properly parse this (in your case since you already use the double quotes I suggest to use the single ones as wrapper):

```
SOME_KEY='{"field1":"some value", "field2": "stops here#this is discarded"}'
```

**Comment by kirillgroshkov** [comment]
Broke us too.

I don't know though what's more "correct" behavior - to require a space before `#` to treat it as comment or not.

**Comment by jonathan-reisdorf** [comment]
Quick collection of patterns I noticed in other tools since yesterday:

vscode: syntax highlighting suggests: unquoted `#` is treated as comment, with or without space
<img width="166" alt="image" src="https://user-images.githubusercontent.com/8958624/150789682-e81fb85e-6f39-4d9e-b214-3ac49bde86f9.png">

Github:
```env
FOO=bar#baz
FOO=bar #baz
FOO="bar#baz"
FOO="bar #baz"
FOO='bar#baz'
FOO='bar #baz'
```

python-dotenv started out where we are but with version 0.10.3 they introduced a check for space character

unix (GNU coreutils) env I've already shared here: https://github.com/motdotla/dotenv/pull/568#issuecomment-1018402106

**Comment by mrliptontea** [comment]
Just ran into this. It's very common for generated secrets to include `#` so something like:

```shell
VAR_WITH_SPECIAL_CHARS=space slash/other@#1!=
```

But unfortunately:

```diff
--- Expected
+++ Received

 {
-  VAR_WITH_SPECIAL_CHARS: "space slash/other@#1!="
+  VAR_WITH_SPECIAL_CHARS: "space slash/other@"
 }
```

**Comment by motdotla** [comment]
@mrliptontea yes, it is very common. We are working on the long term solution for this. Until then, you can do:

1. Downgrade to `13.x`
2. Just put single quotes `'` or double quotes '"` around the value. (that is most likely going to still be the long term solution since it is a best practice)

**Comment by jonathan-reisdorf** [comment]
@mrliptontea even Github highlights the `#1!=` part of your example as a comment 😬 

@motdotla given that the change seems to have broken things for so many, I've created a new PR: https://github.com/motdotla/dotenv/pull/603

**Comment by motdotla** [comment]
Thank you @jonathan-reisdorf.

Patch is in `14.3.2` https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1432-2022-01-25

**Comment by motdotla** [comment]
So patch is in `14.3.2` with thanks to @jonathan-reisdorf.

That said.. `v15.0.0` IS going to implement the rule (and breaking change):

> `#` marks the beginning of a comment (unless when the value is wrapped in quotes)

So our recommendation is to start quoting any values containing `#`. I'm sorry about that. I realize it is an annoyance. We really went back and forth deliberating this one. Long term we think it drives clarity of behavior and we're updating our README examples to use quotes - so that the muscle memory becomes more likely.

PR is here https://github.com/motdotla/dotenv/pull/608 and will likely go out as a release tomorrow or the next day.

**Comment by rmclaughlin-nelnet** [comment]
@motdotla According to OWASP a password can contain any of the following characters https://owasp.org/www-community/password-special-characters. How do you suggest storing passwords, in a way that dotenv can correctly parse them?
