### ISSUE TITLE
Failed to load .env fs.readFileSync is not a function

### ISSUE THREAD

**Issue by djom202** [motdotla/dotenv#680]
I'm actually running into cypress to get my local vars but I got this error and the envs object is empty. I tried to change the location to the .env file nevertheless it still failing.

```
[dotenv][DEBUG] Failed to load /.env fs.readFileSync is not a function
```

I'm using this dependencies:
"dotenv": "^16.0.2",
"cypress": "^10.3.0"
"typescript": "^4.7.4"

**Comment by ComradeAERGO** [comment]
I'm facing the exact same issue. Any luck ?

**Comment by ritschwumm** [comment]
from the cypress docs: "Test modern apps directly in the browser" - could it be cypress just doesn't run your code inside a node.js process? because if it were, the `fs` module really should be available. a browser usually does not have access to the filesystem, so loading a `.env` file from there is not easily doable.

**Comment by motdotla** [comment]
Yes @ritschwumm is correct. fs is not available to the browser.
