### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by Eshtreeli** [motdotla/dotenv#725]
hello i am using (exposdk48)
when i make (eas build --platform ios) this issue appears:
[stderr] 
npm ERR! notarget No matching version found for node-darwin-arm64@17.9.1.

**Comment by arjun-rawal** [comment]
Can you post your package.json?

**Comment by cheng-alvin** [comment]
Hello there! This package is not designed for usage in react native environments because this package is using the fs module which is only available when using node. I suggest you using a module tailored for react native environments. However, If you are using eas for deployment, you can specify the environment variables and secrets inside the eas JSON file. For more information, please visit this website: https://docs.expo.dev/eas-update/environment-variables/ Also please remember the security risks and protect your credentials in a safe environment while using any library for environment variables.

**Comment by cheng-alvin** [comment]
@motdotla We can probably close this one now.
