### ISSUE TITLE
possible to use .env.local to override .env?

### ISSUE THREAD

**Issue by ralyodio** [motdotla/dotenv#738]
I've been using dotenv-flow for this but its stale.

**Comment by motdotla** [comment]
Tell me more about your current setup?

We recommend just one `.env` file rather than having others overwriting - less cognitive load. And then we recommend using [dotenv-vault](https://github.com/dotenv-org/dotenv-vault) to manage multiple environments.

You can create a .env, a .env.production, a .env.staging, etc.

**Comment by qiulang** [comment]
@motdotla I briefly check how [dotenv-vault](https://github.com/dotenv-org/dotenv-vault) works but I feel it is not what I and probably @ralyodio want. We don't need encrypt /decrypt stuff. We just need an `env.local` file to override env setting for local development. Is that possible in dotenv ?

**Comment by ralyodio** [comment]
I don't think so but dotenv-flow does it out of the box.

**Comment by motdotla** [comment]
@nquinlan That's not possible for dotenv. I've historically pushed back against this. Strongly recommend maintaining a single file to decrease complexities and minimize security risk. That said, I acknowledge this isn't that complex and also acknowledge that `.env.local` has been wildly popular with @nextjs.

I'll kick this around more in my head.

In the meantime, I think @ralyodio is correct that dotenv-flow does this out of the box. I'm open to someone creating a dotenv-local that would also do this (just piggy backing on this current lib) and would link to it in the README.
