### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by ChaseKnowlden** [motdotla/dotenv#775]
Node.js 20.6.0 is the first version to include native support for .env files.

https://dev.to/cjreads665/nodejs-2060-say-goodbye-to-dotenv-2ijl.

**Comment by rakeshlanjewar** [comment]
Politely "Hello", This is really mean.

This package is still being used in many other repositories and companies. And the time is yet to come to retire this package.

**Comment by motdotla** [comment]
Node adding built-in `.env` file support is exciting but it's still early, experimental, and there are multiple caveats. 

You can read about the caveats here: https://www.dotenv.org/blog/2023/10/28/node-20-6-0-includes-built-in-support-for-env-files.html

**Comment by motdotla** [comment]
the node team is still working on parity with `dotenv`. it will take some time (years really because many companies are on older versions of node that do not have dotenv support), but we are starting to shift our attention toward **keeping your .env files safe**

here are a couple tools we added you might find useful:

* [precommit hook](https://dotenvx.com/docs/features/precommit) - prevent your `.env` files from being committed to code
* [prebuild hook)(https://dotenvx.com/docs/features/prebuild) - prevent your `.env` files from being included in a docker container

**Comment by quantuminformation** [comment]
atm I'm using node 20, and I tried to use dotenv, but I'm not seeing my vars populated:

`    key: process.env.API_SECRET || "",`

I am just seeing `''` as a value

`.env` at project root

```ts
// stored in /app/data/common.ts

/*
import "dotenv/config";
console.log(process.env); // Log to see all environment variables
*/

import dotenv from 'dotenv';
dotenv.config();
```

**Comment by motdotla** [comment]
@quantuminformation make sure your .env file is in the root of your process.

or, you can consider switching to [dotenvx](https://github.com/dotenvx/dotenvx) - a better `dotenv`, created by yours truly.

**Comment by quantuminformation** [comment]
i ended up just doing this thx:

tsx --env-file=../../.env patch  product products local

../../ is sad
