### ISSUE TITLE
.env returns undefined or must a be string error in console

### ISSUE THREAD

**Issue by wathika-eng** [motdotla/dotenv#822]
Tried some solutions from closed issues e.g https://github.com/motdotla/dotenv/issues/546 and https://stackoverflow.com/questions/44915758/node-process-env-variable-name-returning-undefined but none seems to be working

![image](https://github.com/motdotla/dotenv/assets/71040609/cc2d4a12-e0f7-4806-92a0-2b0d833dd814)

**Comment by Emmo00** [comment]
Hello @wathika-eng , I think the problem is the way you're running the script and the concept of "current working directory"
Given this little script that checks your `cwd` script:
![image](https://github.com/motdotla/dotenv/assets/88244468/a1da6cde-83ee-4971-888d-4f7dbe9e56fe)
And this file Structure:
![image](https://github.com/motdotla/dotenv/assets/88244468/bc45d325-cd50-40a8-9ca4-a862313433c5)
Notice the difference in output when I call the script from outside the `dir` directory with path `dir/script.js` and when I call it from inside the `dir` directory with `script.js`:
![image](https://github.com/motdotla/dotenv/assets/88244468/a3b45155-d804-4ec3-a646-9963f9a7938b)

So even when you're calling `routes/router.js`, your current working directory is still the project's root, so you don't need to specify the path to your `.env` file.

**Comment by wathika-eng** [comment]
Worked after deleting the path I had specified
